const SKY_DEPTH = -20
const BACKGROUND_DEPTH = -10
const BACKGROUND_COMPONENT_DEPTH = -5
const MIDDLEGROUND_DEPTH = -1
const PLAYER_DEPTH = 0
const FOREGROUND_DEPTH = 10

export default {
  SKY_DEPTH,
  BACKGROUND_DEPTH,
  BACKGROUND_COMPONENT_DEPTH,
  MIDDLEGROUND_DEPTH,
  PLAYER_DEPTH,
  FOREGROUND_DEPTH,
}
